apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: app1
    function: front-end

spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports:
      - containerPort: 8080

  
# kubectl get pods --selector app=app1

# kubectl get all --selector env=prod,bu=finance,tier=frontend

apiVersion: apps/v1 
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:                      # this labels for only replciass
    app: myapp   
    type: front-end

spec:
  selector:
    matchLabels:   #  it should be labels on pod metadata section same as it
      type: front-end
  replicas: 2
  template:
    metadata:
      name: myapp-prod # pod name
      labels:
        app: myapp     # this pods labels 
        type: front-end
    spec:
      containers:  # is list and array
      - name: nginx-container
        image: nginx 
