apiVersion: v1
kind: Namespace
metadata:
  name: dev


# kubectl create -f namespace.yaml

# kubectl create namespace dev

# kubectl config set-context $(kubectl config current-context) --namespace=dev

# kubectl get pods --namespace=prod

# kubectl get pods --all-namespaces