apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod # pod name
  labels:
    app: myapp     # labels 
    type: front-end
spec:
  priorityClassName: high-priority
  containers:  # is list and array
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 

# kubectl create -f pod-definition.yaml
# kubectl describe pod myapp-prod

