apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-12-16T13:55:56Z"
  name: elephant
  namespace: default
  resourceVersion: "1016"
  uid: 8b567121-438e-4cec-8faa-ac6e14a8ab5a
spec:
  containers:
  - args:
    - --vm
    - "1"
    - --vm-bytes
    - 15M
    - --vm-hang
    - "1"
    command:
    - stress
    image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        memory: 20Mi
      requests:
        memory: 5Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts: