apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod # pod name
  labels:
    app: myapp     # labels 
    type: front-end
spec:
  containers:  # is list and array
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 
      resources:
        requests:
          memory: "1.5Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 1.5
          

# kubectl create -f pod-definition.yaml
# kubectl describe pod myapp-prod
# kubectl get pod webapp -o yaml > my-new-pod.yaml
