apiVersion: kubescheduler.config.k8s.io/v1
kind: kubeschedulerConfiguration
profiles:
  - schedulerName: default-scheduler


apiVersion: kubescheduler.config.k8s.io/v1
kind: kubeschedulerConfiguration
profiles:
  - schedulerName: my-scheduler


##############################

apiVersion: v1
kind: Pod
metadata:
  name: myapp-prod # pod name
  labels:
    app: myapp     # labels 
    type: front-end
spec:
  containers:  # is list and array
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
  schedulerName: my-scheduler 

  ##################

  apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-scheduler
  name: my-scheduler
  namespace: kube-system
spec:
  serviceAccountName: my-scheduler
  containers:
  - command:
    - /usr/local/bin/kube-scheduler
    - --config=/etc/kubernetes/my-scheduler/my-scheduler-config.yaml
    image: registry.k8s.io/kube-scheduler:v1.27.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 15
    name: kube-second-scheduler
    readinessProbe:
      httpGet:
        path: /healthz
        port: 10259
        scheme: HTTPS
    resources:
      requests:
        cpu: '0.1'
    securityContext:
      privileged: false
    volumeMounts:
      - name: config-volume
        mountPath: /etc/kubernetes/my-scheduler
  hostNetwork: false
  hostPID: false
  volumes:
    - name: config-volume
      configMap:
        name: my-scheduler-config

$ kubectl label nodes node-1 size=Large
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  -	name: nginx
    image: nginx
  nodeSelector:
    size: Large