apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color

spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      # env:
      #   - name: APP_COLOR
      #     value: blue
      #   - name: APP_MODE
      #     value: prod
      # env:
      #   - name: APP_COLOR
      #     valueFrom:
      #       configMapKeyRef:
      #         name: app-config
      #         key: APP_COLOR
      envFrom:
        - configMapRef:
            name: app-config


# kubectl create configmap <config-name> --from-literal=<key>=<value>
# kubectl create configmap app-config --from-literal=APP_COLOR=blue
                                      # --from-literal=APP_MODE=prod


# kubectl create configmap app-config --from-file=app_config.properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod
  




