apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      ports:
        - containerPort: 8080
      env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_HOST
      envFrom:
        - secretRef:
            name: app-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  DB_HOST: bXlzcWw=
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzcw== 


secrets are not encrypted. only encoded
don't push secets in scm along with code
secrets are not enrcrypt in ETCD


# echo -n 'pass' | base64

# echo -n 'cGFzcw==' | base64 --decode

# kubectl create secret generic <secret-name> --from-literal=<key>=<value>
# kubectl create secret generic app-secret --from-literal=DB_HOST=mysql
                                      # --from-literal=PASSWORD=prod
                                      # --from-literal=USERNAME=root

# kubectl get secrets
# kubectl get secret app-secret -o yaml