apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod

spec:
  containers:
    - name: ubuntu-sleeper-container 
      image: ubuntu-sleeper
      command: ["sleep2.0"]       # this is the file wil override docker ENTRYPOINT        
      args: ["10"]                # this is the file wil override the CMD

---
apiVersion: v1 
kind: Pod 
metadata:
  name: ubuntu-sleeper-2 
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command:
      - "sleep"
      - "5000"