apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp

spec:
  initContainers:
  - image: busybox
    name: red-initcontainer
    command:
      - "sleep"
      - "20"
  containers:
    - name: simple-webapp
      image: simple-webapp
      ports:
        - containerPort: 8080
    - name: log-agent
      image: log-agent

kubectl get pod orange -o yaml > /root/orange.yaml
kubectl logs podname -c containername
kubectl -n elastic-stack logs kibana
kubectl exec --stdin --tty shell-demo -- /bin/bash


apiVersion: v1
kind: Pod
metadata:
name: app
namespace: elastic-stack
labels:
name: app
spec:
containers:

name: app
image: kodekloud/event-simulator
volumeMounts:

mountPath: /log
name: log-volume
name: sidecar
image: kodekloud/filebeat-configured
volumeMounts:

mountPath: /var/log/event-simulator/
name: log-volume
volumes:

name: log-volume
hostPath:
# directory location on host
path: /var/log/webapp
# this field is optional
type: DirectoryOrCreate